### ISSUE TITLE
Resize / Re-position all images of sequence

### ISSUE THREAD

**Issue by sbuschjaeger** [xtingray/tupitube.desk#56]
Hi,

is there any way to place / resize all images of an image sequence at once? I managed to import a longer sequence (> 200 pictures) but it would always place them in the middle of the canvas / layer. Resize / reposition of single images works fine, but I don't really want to do that for 200 images.

**Comment by xtingray** [comment]
Hi!
Currently, there is no feature to set parameters for the "Import Image Sequence" action. Nevertheless, I already added your requirement to our To-Do list as it has a lot of sense.
Now, if you want to, I can help you to fix your current project if you send me the files, telling me the position and size you want to for the images. My email is info@maefloresta.com, in case you are interested in my help.

**Comment by sbuschjaeger** [comment]
Hey, thanks for the quick reply and thanks for the offer! I get back to that, but maybe you could point me in the right direction here first:
You suggestion got me thinking, that I could basically modify the project files directly. If I understand the source code correctly, then you use QuaZIP for compression/decompression. So far I was able to unzip the project files and find the corresponding XML-like *.tps files. I think I just have to copy/paste the corresponding <frame> ... </frame>-parts here, correct?
Unfortunately, I was not able to zip the changed files again to test my theory. Judging by the file size and infos from `zipinfo` QuaZIP seems to have some different default compression flags than regular `zip`? Maybe you have an idea how to zip the files again, or do I have to write a small program with QuaZip to be fully compatible?

**Comment by xtingray** [comment]
You are right. You could disassemble any .tup file, modify it and then pack it back. My only worry it's about your time, you will have to invest several hours understanding the structure of the format.
Anyway, the procedure  I use to pack an uncompressed project from any Unix system is this:
% find project_dir -type f | zip -@ project.tup

**Comment by sbuschjaeger** [comment]
Thanks for the comment. Worked like a charm!
