### ISSUE TITLE
ffmpeg codecs

### ISSUE THREAD

**Issue by pannet1** [xtingray/tupitube.desk#63]
i am using endeavor OS (a flavor of arch linux). I already installed ffmpeg. can you please confirm what else i should install as dependency. 

![image](https://user-images.githubusercontent.com/12350276/180612844-8e02f5f2-7020-41ab-a831-9252f84c7648.png)

**Comment by xtingray** [comment]
To start tracing the issue, I recommend you to try this binary self-contained package: 
https://tupitube.com/installers/tupitube_0.2.18_linux_x64.sh
It includes the ffmpeg libraries required to export videos, so if it works then we will have a solid reference to start comparing ffmpeg versions. 
Once you execute the .sh file, a folder called "TupiTube_Desk" will be created in the same path. Inside that folder you will find a launcher script called "tupitube.desk". You just have to execute it.
Please, let me know if you have any additional questions.

**Comment by pannet1** [comment]
Thanks a lot. It works. Should be some dependency issues with the AUR package.
