### ISSUE TITLE
Show Tips Issue

### ISSUE THREAD

**Issue by lxlalexlxl** [xtingray/tupitube.desk#79]
1) Start TupiTube and create new project.
2) Select Object Selection tool.
3) Click Sow Tips button.
After that, the tools located at the bottom of the window disappear. See attachment.

TupiTube 0.2.21
Linux Mint 21.2 Cinnamon

![bug](https://github.com/xtingray/tupitube.desk/assets/10048257/b15e3b70-2456-4f2c-b629-38f53d5b8f12)
![OK](https://github.com/xtingray/tupitube.desk/assets/10048257/11a1a1c1-bfb8-4638-825a-451e77f41365)

**Comment by xtingray** [comment]
Hi! 
It would be handy if you could share the display resolution of your environment. You can get this information by using the command **xdpyinfo**
Thanks!

**Comment by lxlalexlxl** [comment]
This is part of the xdpyinfo command output:

screen #0:
  dimensions:    1366x768 pixels (361x203 millimeters)
  resolution:    96x96 dots per inch

**Comment by xtingray** [comment]
Please, try this installer and let me know if the issue is fixed:
https://tupitube.com/tmp/TupiTube_Desk_0.2.21_x64.sh

Thanks!

**Comment by lxlalexlxl** [comment]
This is much better. But now there is space left under the prompts that can be used. This will reduce the need for scrolling.
![place](https://github.com/xtingray/tupitube.desk/assets/10048257/09556066-079f-4d1f-9582-0e8c8299d641)

**Comment by xtingray** [comment]
Please, try it again:
https://tupitube.com/tmp/TupiTube_Desk_0.2.21_x64.sh

**Comment by lxlalexlxl** [comment]
Fine. But the Nodes Selection tool and the Line tool has the same problem.
![LineTool](https://github.com/xtingray/tupitube.desk/assets/10048257/60dcd527-353f-4ac4-80a4-5239d9908997)

**Comment by xtingray** [comment]
Fixing Object Selection, Nodes Selection and Shapes (including Line):
https://tupitube.com/tmp/TupiTube_Desk_0.2.21_x64.sh

**Comment by lxlalexlxl** [comment]
Now works fine.

**Comment by xtingray** [comment]
That's great!
