### ISSUE TITLE
Rotation Tween Issue

### ISSUE THREAD

**Issue by lxlalexlxl** [xtingray/tupitube.desk#80]
1) Create new project an draw rectangle.
2) Start adding Rotation tween to it.
3) Select **partial** for the type.

Result:
1) the tools located at the bottom of the window disappear;
2) buttons for applying/canceling the tween are hidden by taskbar.

Linux Mint 21.2 Cinnamon
Screen resolution: 1366*768
![rotation](https://github.com/xtingray/tupitube.desk/assets/10048257/23241911-dfca-4520-a255-093c2e163686)

**Comment by xtingray** [comment]
The Rotation Tween interface was refactored. Please, try this installer:
https://tupitube.com/tmp/TupiTube_Desk_0.2.21_x64.sh

**Comment by lxlalexlxl** [comment]
Thanks. That's much better.

**Comment by xtingray** [comment]
Cool! Issue fixed.
