### ISSUE TITLE
Rotation Tween Removing Issue

### ISSUE THREAD

**Issue by lxlalexlxl** [xtingray/tupitube.desk#82]
1. Create a new project an draw two rectangles.
2. Add a rotation tween to the two rectangles together. Set end frame to 100 and apply tween. The player shows two rotating rectangles.
3. Delete the tween you just added. Now the player shows one rotating rectangle, that is, the tween has not been removed completely.

**Comment by xtingray** [comment]
The "Remove Tween" issue has been fixed. Please, try this installer to confirm the fix:
https://tupitube.com/tmp/TupiTube_Desk_0.2.21_x64.sh

**Comment by lxlalexlxl** [comment]
This version works fine.
